"use client";
import { useEffect, useRef, useState } from 'react';
import { MapPin, CalendarDays, Church, Heart, Wine, Music2, Sparkles, Send, Check, ArrowUp, Mail } from 'lucide-react';
import { Accordion, AccordionItem, AccordionTrigger, AccordionContent } from '@/components/ui/accordion';
import { RadioGroup, RadioGroupItem } from '@/components/ui/radio-group';
import { wedding } from './wedding';
const icons = {church:Church,heart:Heart,wine:Wine,music:Music2,sparkles:Sparkles};
function CalendarLink({recovery=false}:{recovery?:boolean}) {
 function download(){const text=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Camille and Antoine//Wedding//EN','BEGIN:VEVENT',`UID:${recovery?'recovery':'wedding'}-20270612@camille-antoine`,'DTSTAMP:20260912T000000Z',`DTSTART:${recovery?'20270613T100000Z':'20270612T150000Z'}`,`DTEND:${recovery?'20270613T140000Z':'20270612T210000Z'}`,`SUMMARY:${recovery?'Camille and Antoine - Recovery Day':'The Wedding of Camille and Antoine'}`,`LOCATION:${recovery?'Le Comptoir des Halles - 4 Rue Monge - Beaune':'Château de Belvent - Gevrey-Chambertin - France'}`,'END:VEVENT','END:VCALENDAR',''].join('\r\n');const url=URL.createObjectURL(new Blob([text],{type:'text/calendar;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=recovery?'recovery-day.ics':'camille-antoine-wedding.ics';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 return <button className="text-link" onClick={download}><CalendarDays size={14}/> Add to calendar</button>
}
export default function Celebration(){
 const [attendance,setAttendance]=useState('yes');const [shuttle,setShuttle]=useState('no');const [status,setStatus]=useState('idle');const [error,setError]=useState('');const key=useRef('');const form=useRef<HTMLFormElement>(null);
 useEffect(()=>{const els=document.querySelectorAll('.reveal');const observer=new IntersectionObserver(items=>items.forEach(item=>{if(item.isIntersecting){item.target.classList.add('visible');observer.unobserve(item.target)}}),{threshold:.08});els.forEach(el=>observer.observe(el));return()=>observer.disconnect()},[]);
 async function send(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(status==='sending')return;const data=new FormData(e.currentTarget);if(!key.current)key.current=crypto.randomUUID();setStatus('sending');setError('');try{const r=await fetch('/api/rsvp',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:key.current,name:data.get('name'),attendance,shuttle:attendance==='yes'?shuttle:'no',diet:attendance==='yes'?data.get('diet'):'',message:data.get('message'),website:data.get('website')})});if(!r.ok)throw new Error('Your reply could not be saved. Please try again in a moment.');setStatus('success')}catch(err){setStatus('error');setError(err instanceof Error?err.message:'Please try again.')}}
 useEffect(()=>{const context=(document as Document&{modelContext?:{registerTool:(tool:unknown,options:unknown)=>unknown}}).modelContext;if(!context)return;const controller=new AbortController();try{Promise.resolve(context.registerTool({name:'navigate_wedding_invitation',description:'Navigate to a wedding invitation section. Does not send an RSVP.',inputSchema:{type:'object',properties:{section:{type:'string',enum:['details','timeline','faq','rsvp']}},required:['section'],additionalProperties:false},annotations:{readOnlyHint:false},execute:(input:unknown)=>{const s=(input as {section?:string})?.section;if(!s||!['details','timeline','faq','rsvp'].includes(s))throw Error('Unknown invitation section');document.getElementById(s)?.scrollIntoView({behavior:'instant'});return{section:s}}},{signal:controller.signal})).catch(()=>{})}catch{}return()=>controller.abort()},[]);
 return <>
 <section id="details" className="venue section reveal"><div className="venue-frame"><p className="eyebrow">Where we celebrate</p><h2>Ceremony & Reception</h2><img src="/images/chateau.png" alt="Watercolor illustration of a French château with green shutters and a formal garden" className="chateau" loading="lazy" width="1536" height="1024"/><h3>{wedding.venue}</h3><p className="eyebrow venue-address">Gevrey-Chambertin · Bourgogne</p><p className="script">Saturday, 12 June 2027</p><div className="venue-times"><p><span>Ceremony</span>The Orangery · 5:00 PM</p><p><span>Reception</span>The Wine Cellar · 7:00 PM</p></div><div className="venue-links"><a className="text-link" href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(wedding.venue+' '+wedding.address)}`} target="_blank" rel="noreferrer"><MapPin size={14}/>Open in maps</a><CalendarLink/></div></div></section>
 <section className="dress section reveal"><p className="script">A little occasion to dress up</p><h2>Dress Code</h2><div className="fine-rule"/><h3>Black Tie</h3><p>The celebration will be held on the grand terrace and lawn.<br/>Please choose footwear suited to the gardens.</p><div className="palette" aria-label="Wedding palette: ivory, sage, olive, forest green and black"><span style={{background:'#eee8db'}}/><span style={{background:'#b1b6a2'}}/><span style={{background:'#6f7b59'}}/><span style={{background:'#293e2e'}}/><span style={{background:'#222721'}}/></div><p className="script">An evening of elegance, a night to remember.</p></section>
 <section id="timeline" className="timeline section reveal"><h2>The order of the day</h2><p className="script">From the first hello to the last dance</p><ol>{wedding.timeline.map((item)=>{const Icon=icons[item.icon as keyof typeof icons];return <li key={item.time}><div className="timeline-icon"><Icon size={29} strokeWidth={1}/></div><div className="timeline-copy"><time>{item.time}</time><h3>{item.title}</h3><p>{item.detail}</p></div></li>})}</ol><p className="timeline-note script">Our ceremony will take place in the Orangery of Château de Belvent, followed by an aperitif in the rose garden, dinner and dancing in the old wine cellar.</p></section>
 <section className="recovery section reveal"><div><p className="eyebrow">Join us the day after</p><h2>One more day together</h2><p className="script">Recovery Day</p><img src="/images/chateau.png" alt="French garden terrace illustration" className="recovery-art" loading="lazy" width="1536" height="1024"/></div><div className="recovery-copy"><h3>Le Comptoir des Halles</h3><p className="eyebrow">Garden terrace</p><div className="recovery-date"><span>Sunday, 13 June 2027</span><span>From 12 PM</span></div><p>4 Rue Monge, Beaune<br/><span className="script">Bourgogne, France</span></p><p className="recovery-note">A relaxed afternoon of good food, wine and reminiscing about the night before. We would love to see you there.</p><div className="venue-links"><a className="text-link" href="https://www.google.com/maps/search/?api=1&query=Le+Comptoir+des+Halles+4+Rue+Monge+Beaune" target="_blank" rel="noreferrer"><MapPin size={14}/>Open in maps</a><CalendarLink recovery/></div></div></section>
 <section className="gifts section reveal"><div className="gift-frame"><Heart size={26} strokeWidth={1}/><h2>Gifts</h2><p className="script">Your presence at our wedding is the greatest gift of all. Should you wish to celebrate with a gift, a wishing well will be available at the reception.</p><span className="gift-signature">With love, C & A</span></div></section>
 <section id="faq" className="faq section reveal"><p className="script">A few things you might be wondering</p><h2>Questions & answers</h2><Accordion type="single" collapsible className="faq-list">{wedding.faqs.map(([q,a],i)=><AccordionItem key={q} value={String(i)}><AccordionTrigger>{q}</AccordionTrigger><AccordionContent>{a}</AccordionContent></AccordionItem>)}</Accordion></section>
 <section id="rsvp" className="rsvp section reveal"><Mail size={43} strokeWidth={.7} className="rsvp-icon"/><h2>We saved you a seat</h2><p className="script">Kindly RSVP by {wedding.deadline}</p>{status==='success'?<div className="rsvp-success" role="status"><Check size={32} strokeWidth={1}/><h3>Thank you for your reply</h3><p>{attendance==='yes'?'We cannot wait to celebrate with you.':'You will be missed. Thank you for letting us know.'}</p><p className="script">With love, Camille & Antoine</p></div>:<form ref={form} onSubmit={send}><label htmlFor="name">Your full name <span aria-hidden="true">*</span></label><input id="name" name="name" required minLength={2} maxLength={150} autoComplete="name" placeholder="Enter your full name"/><fieldset><legend>Will you be attending? <span aria-hidden="true">*</span></legend><RadioGroup value={attendance} onValueChange={setAttendance} name="attendance"><label className="radio-label" htmlFor="attend-yes"><RadioGroupItem id="attend-yes" value="yes"/>Joyfully accepts</label><label className="radio-label" htmlFor="attend-no"><RadioGroupItem id="attend-no" value="no"/>Regretfully declines</label></RadioGroup></fieldset><p className="form-note script">Your invitation is for you only. We love your little ones; however, our wedding is adults only.</p>{attendance==='yes'&&<><label htmlFor="diet">Allergies or dietary requirements</label><textarea id="diet" name="diet" rows={3} maxLength={1000} placeholder="Let us know how we can look after you"/><fieldset><legend>Would you like a seat on our shuttle from Beaune?</legend><RadioGroup name="shuttle" value={shuttle} onValueChange={setShuttle}><label className="radio-label" htmlFor="shuttle-yes"><RadioGroupItem id="shuttle-yes" value="yes"/>Yes, please save me a seat</label><label className="radio-label" htmlFor="shuttle-no"><RadioGroupItem id="shuttle-no" value="no"/>No, I will arrange my own transport</label></RadioGroup></fieldset></>}<label htmlFor="message">A personal message for the couple</label><textarea id="message" name="message" maxLength={2000} rows={4} placeholder="A wish, a memory, something you would like us to read…"/><div className="honeypot" aria-hidden="true"><label htmlFor="website">Website</label><input id="website" name="website" tabIndex={-1} autoComplete="off"/></div>{error&&<p className="form-error" role="alert">{error}</p>}<button type="submit" className="submit-rsvp" disabled={status==='sending'}><Send size={15}/>{status==='sending'?'Sending your reply…':'Send RSVP'}</button></form>}</section>
 <footer><p className="script">The beginning of our forever</p><h2>Camille <i>&</i> Antoine</h2><p className="eyebrow">12 June 2027 · Burgundy, France</p><img src="/images/chateau.png" alt="" width="1536" height="1024" loading="lazy"/><a href="#top" className="back-top"><ArrowUp size={14}/>Back to the invitation</a></footer>
 </>
}
